# Generated by Django 3.1.7 on 2021-03-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDLS_API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSID', models.CharField(max_length=250)),
                ('RSSI', models.FloatField(max_length=250)),
                ('Time', models.DateTimeField()),
                ('BSSID', models.CharField(max_length=250)),
                ('Location_ID', models.CharField(max_length=250)),
            ],
        ),
    ]
